// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrjkleghggqkppttvuau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyamtsZWdoZ2dxa3BwdHR2dWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzM5NzEsImV4cCI6MjA2NTYwOTk3MX0.fHQ4BgTnWHZWZdUYkNlY72VJjy14QA1N77TvIxRSxRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);