// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iilqksoqgrkcqzparqon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpbHFrc29xZ3JrY3F6cGFycW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTEzNTEsImV4cCI6MjA2NjU2NzM1MX0.zRdPrX3h8ir14c7T2fR8Th5zJVc5Z2PtdDCZtfq5T0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);